# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\OfflineHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.btnOK = QtWidgets.QDialogButtonBox(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.btnOK.setOrientation(QtCore.Qt.Horizontal)
        self.btnOK.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnOK.setObjectName("btnOK")
        self.lblHelp = QtWidgets.QLabel(Dialog)
        self.lblHelp.setGeometry(QtCore.QRect(10, 10, 621, 431))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(52)
        self.lblHelp.setFont(font)
        self.lblHelp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHelp.setWordWrap(True)
        self.lblHelp.setObjectName("lblHelp")

        self.retranslateUi(Dialog)
        self.btnOK.accepted.connect(Dialog.accept) # type: ignore
        self.btnOK.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Offline Help Window"))
        self.lblHelp.setText(_translate("Dialog", "Sorry, we\'re offline! Come back later!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
