# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\StudentsTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#########################################################################
#                                                                       #
#                            UI Generation                              #
#                                                                       #
#########################################################################

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication

import mysql.connector
from PyQt5.QtWidgets import QMessageBox

from windows import StudentsDialog

QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)  # Enable high DPI scaling
QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)  # Use high DPI icons


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 681, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(700, 80, 81, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNew = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnNew.setFont(font)
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout.addWidget(self.btnNew)
        self.btnEdit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnClose = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClose.setOrientation(QtCore.Qt.Vertical)
        self.btnClose.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btnClose.setCenterButtons(False)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 10, 221, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblStudentID = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentID.setFont(font)
        self.lblStudentID.setObjectName("lblStudentID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblStudentID)
        self.lblGender = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender.setFont(font)
        self.lblGender.setObjectName("lblGender")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.txtStudentID = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtStudentID.setFont(font)
        self.txtStudentID.setText("")
        self.txtStudentID.setObjectName("txtStudentID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtStudentID)
        self.cmbGender = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cmbGender.setFont(font)
        self.cmbGender.setObjectName("cmbGender")
        self.cmbGender.addItem("")
        self.cmbGender.addItem("")
        self.cmbGender.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbGender)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 10, 311, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblFirstName = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblFirstName)
        self.txtFirstName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtFirstName.setFont(font)
        self.txtFirstName.setObjectName("txtFirstName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtFirstName)
        self.lblLastName = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblLastName)
        self.txtLastName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtLastName.setFont(font)
        self.txtLastName.setObjectName("txtLastName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtLastName)
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(10, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitle.setFont(font)
        self.lblTitle.setAcceptDrops(False)
        self.lblTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTitle.setAutoFillBackground(False)
        self.lblTitle.setStyleSheet("background-color: rgb(22, 9, 88);\n"
"color: rgb(255, 255, 255);")
        self.lblTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTitle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblTitle.setLineWidth(3)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(700, 10, 81, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSearch = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout_2.addWidget(self.btnSearch)
        self.btnClear = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout_2.addWidget(self.btnClear)
        self.frameTop = QtWidgets.QFrame(Dialog)
        self.frameTop.setGeometry(QtCore.QRect(140, 10, 641, 61))
        self.frameTop.setStyleSheet("color: rgb(255, 255, 0);")
        self.frameTop.setFrameShape(QtWidgets.QFrame.Box)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTop.setLineWidth(2)
        self.frameTop.setObjectName("frameTop")
        self.frameRight = QtWidgets.QFrame(Dialog)
        self.frameRight.setGeometry(QtCore.QRect(700, 80, 81, 491))
        self.frameRight.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameRight.setLineWidth(2)
        self.frameRight.setObjectName("frameRight")
        self.frameRight.raise_()
        self.frameTop.raise_()
        self.horizontalLayoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.lblTitle.raise_()
        self.verticalLayoutWidget_2.raise_()

        self.retranslateUi(Dialog)
        self.btnClose.accepted.connect(Dialog.accept) # type: ignore
        self.btnClose.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Students Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Student ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Address"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Credits"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Current Status"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Major"))
        self.btnNew.setText(_translate("Dialog", "New"))
        self.btnEdit.setText(_translate("Dialog", "Edit"))
        self.btnDelete.setText(_translate("Dialog", "Delete"))
        self.lblStudentID.setText(_translate("Dialog", "Student ID:"))
        self.lblGender.setText(_translate("Dialog", "Gender:"))
        self.cmbGender.setItemText(0, _translate("Dialog", "M"))
        self.cmbGender.setItemText(1, _translate("Dialog", "F"))
        self.cmbGender.setItemText(2, _translate("Dialog", "O"))
        self.lblFirstName.setText(_translate("Dialog", "First Name:"))
        self.lblLastName.setText(_translate("Dialog", "Last Name:"))
        self.lblTitle.setText(_translate("Dialog", "Students Table"))
        self.btnSearch.setText(_translate("Dialog", "Search"))
        self.btnClear.setText(_translate("Dialog", "Clear"))

#####################     End UI Generation     #####################

    def initialSetup(self):
        self.setupEvents()
        self.setupDatabase()
        self.refreshStudents()
        # self.setupDatabase()
        # self.setupCombobox()
        # self.setValues()

    #########################################################################
    #                                                                       #
    #                            Events                                     #
    #                                                                       #
    #########################################################################

    def setupEvents(self):
        self.btnNew.clicked.connect(self.btnNewStudents_clicked)
        self.btnEdit.clicked.connect(self.btnEditStudents_clicked)
        self.btnDelete.clicked.connect(self.btnDeleteStudents_clicked)
        self.btnSearch.clicked.connect(self.btnSearch_clicked)
        self.btnClear.clicked.connect(self.btnClear_clicked)


    def btnNewStudents_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = StudentsDialog.Ui_StudentsDialog()
        form.setupUi(Dialog, None)  # None -> no list, no need to send data when creating a new record
        result = Dialog.exec_()

        if result == 1:  # This means the user clicked OK
            #   Get the list of results from dialog
            listValues = form.getValues()

            cursor = self.cnx.cursor()

            query = "Select * From students"

            cursor.execute(query)

            largestID = 0
            # Retreive the largest ID
            for (ID, First_Name, Last_Name, Gender, Email, Address, Credits, Status, Major) in cursor:
                if(ID > largestID):
                    largestID = ID

            largestID += 1
            listValues[0] = str(largestID)

            print(listValues)

            # Insert the values in the database
            self.insertStudents(listValues)

            # Refresh the table
            self.refreshStudents()


    def btnEditStudents_clicked(self):
        currentRow = self.tableWidget.currentRow()

        if currentRow == -1:
            QMessageBox.warning(None, "Select Row", "Please select row first")
            return

        listValues = []
        listValues.append(self.tableWidget.item(currentRow, 0).text())
        listValues.append(self.tableWidget.item(currentRow, 1).text())
        listValues.append(self.tableWidget.item(currentRow, 2).text())
        listValues.append(self.tableWidget.item(currentRow, 3).text())
        listValues.append(self.tableWidget.item(currentRow, 4).text())
        listValues.append(self.tableWidget.item(currentRow, 5).text())
        listValues.append(self.tableWidget.item(currentRow, 6).text())
        listValues.append(self.tableWidget.item(currentRow, 7).text())
        listValues.append(self.tableWidget.item(currentRow, 8).text())

        print(listValues)

        Dialog = QtWidgets.QDialog()
        form = StudentsDialog.Ui_StudentsDialog()
        form.setupUi(Dialog, listValues)
        result = Dialog.exec_()

        if result == 1:  # This means the user clicked OK
            #   Get the list of results from dialog
            newValues = form.getValues()
            newValues[0] = listValues[0]  # Set the ID to the original value

            # Insert the values in the table
            # rowCount = self.tblCategories.rowCount()
            # self.tblCategories.insertRow(rowCount)  # Create new row at the end
            # self.tblCategories.setItem(rowCount, 0, QTableWidgetItem(listValues[0]))
            # self.tblCategories.setItem(rowCount, 1, QTableWidgetItem(listValues[1]))

            # Insert the values in the database
            self.updateStudents(newValues)

            # Refresh the table
            self.refreshStudents()


    def btnDeleteStudents_clicked(self):
        currentRow = self.tableWidget.currentRow()

        if currentRow == -1:
            QMessageBox.warning(None, "Select Row", "Please select row first")
            return

        answer = QMessageBox.question(
            None,
            "Delete row?",
            "Are you sure you want to delete this row?",
            QMessageBox.StandardButton.Yes |
            QMessageBox.StandardButton.No
        )

        if answer == QMessageBox.StandardButton.Yes:
            ID = self.tableWidget.item(currentRow, 0).text()

            # Delete the values in the database
            self.deleteStudents(ID)
            self.refreshStudents()


    def btnSearch_clicked(self):
        ID = self.txtStudentID.text()
        FirstName = self.txtFirstName.text()
        LastName = self.txtLastName.text()
        Gender = self.cmbGender.currentText()

        self.filterStudents(ID, FirstName, LastName, Gender)


    def btnClear_clicked(self):
        self.txtStudentID.setText("")
        self.txtFirstName.setText("")
        self.txtLastName.setText("")
        self.cmbGender.setCurrentIndex(0)
        self.refreshStudents()


    #########################################################################
    #                                                                       #
    #                            Database                                   #
    #                                                                       #
    #########################################################################

    def setupDatabase(self):
        self.connect()

    def connect(self):
        self.cnx = mysql.connector.connect(user="root",
                                            password="12345678",
                                            host="127.0.0.1",
                                            database="tracle")

    def refreshStudents(self):
        self.tableWidget.setRowCount(0)
        cursor = self.cnx.cursor()

        query = "Select * From students Order by ID Asc"

        cursor.execute(query)

        for(ID, First_Name, Last_Name, Gender, Email, Address, Credits, Status, Major) in cursor:
            rowCount = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rowCount)
            self.tableWidget.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(str(ID)))
            self.tableWidget.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(First_Name))
            self.tableWidget.setItem(rowCount, 2, QtWidgets.QTableWidgetItem(Last_Name))
            self.tableWidget.setItem(rowCount, 3, QtWidgets.QTableWidgetItem(Gender))
            self.tableWidget.setItem(rowCount, 4, QtWidgets.QTableWidgetItem(Email))
            self.tableWidget.setItem(rowCount, 5, QtWidgets.QTableWidgetItem(Address))
            self.tableWidget.setItem(rowCount, 6, QtWidgets.QTableWidgetItem(str(Credits)))
            self.tableWidget.setItem(rowCount, 7, QtWidgets.QTableWidgetItem(Status))
            self.tableWidget.setItem(rowCount, 8, QtWidgets.QTableWidgetItem(Major))

        cursor.close()


    def insertStudents(self, a_listValues):
        cursor = self.cnx.cursor()

        query = ("Insert Into students "
                 "(ID, First_Name, Last_Name, Gender, Email, Address, Credits, Current_Status, Major) "
                 "Values (%s, %s, %s, %s, %s, %s, %s, %s, %s)")

        values = a_listValues

        cursor.execute(query, values)

        self.cnx.commit()

        cursor.close()


    def updateStudents(self, a_listValues):
        cursor = self.cnx.cursor()

        query = ("Update students "
                 "Set First_Name = %s, Last_Name = %s, Gender = %s, Email = %s, Address = %s, Credits = %s, Current_Status = %s, Major = %s "
                 "Where ID = %s")

        values = a_listValues

        values.append(values.pop(0))

        print(values)

        cursor.execute(query, values)

        self.cnx.commit()

        cursor.close()


    def deleteStudents(self, a_ID):
        cursor = self.cnx.cursor()

        query = ("Delete From students "
                 "Where ID = %s")

        values = (a_ID,)

        cursor.execute(query, values)

        self.cnx.commit()

        cursor.close()


    def filterStudents(self, _ID, _First_Name, _Last_Name, _Gender):
        self.tableWidget.setRowCount(0)

        cursor = self.cnx.cursor()

        query = "Select * " \
                "From students " \
                "WHERE (ID = %s OR %s IS NULL OR %s = '') AND " \
                "(First_Name = %s OR %s IS NULL OR %s = '') AND " \
                "(Last_Name = %s OR %s IS NULL OR %s = '') AND " \
                "(Gender = %s OR %s IS NULL OR %s = '') " \


        values = []
        values.append(_ID)
        values.append(_ID)
        values.append(_ID)
        values.append(_First_Name)
        values.append(_First_Name)
        values.append(_First_Name)
        values.append(_Last_Name)
        values.append(_Last_Name)
        values.append(_Last_Name)
        values.append(_Gender)
        values.append(_Gender)
        values.append(_Gender)

        print(values)

        cursor.execute(query, values)

        for (ID, First_Name, Last_Name, Gender, Email, Address, Credits, Status, Major) in cursor:
            rowCount = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rowCount)
            self.tableWidget.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(str(ID)))
            self.tableWidget.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(First_Name))
            self.tableWidget.setItem(rowCount, 2, QtWidgets.QTableWidgetItem(Last_Name))
            self.tableWidget.setItem(rowCount, 3, QtWidgets.QTableWidgetItem(Gender))
            self.tableWidget.setItem(rowCount, 4, QtWidgets.QTableWidgetItem(Email))
            self.tableWidget.setItem(rowCount, 5, QtWidgets.QTableWidgetItem(Address))
            self.tableWidget.setItem(rowCount, 6, QtWidgets.QTableWidgetItem(str(Credits)))
            self.tableWidget.setItem(rowCount, 7, QtWidgets.QTableWidgetItem(Status))
            self.tableWidget.setItem(rowCount, 8, QtWidgets.QTableWidgetItem(Major))

        cursor.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
