# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\StudentsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#########################################################################
#                                                                       #
#                            UI Generation                              #
#                                                                       #
#########################################################################

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication

QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)  # Enable high DPI scaling
QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)  # Use high DPI icons


class Ui_StudentsDialog(object):
    def setupUi(self, StudentsDialog, listValues):
        StudentsDialog.setObjectName("StudentsDialog")
        StudentsDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(StudentsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 260, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(StudentsDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_DialogExpenses = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_DialogExpenses.setContentsMargins(6, 6, 6, 6)
        self.formLayout_DialogExpenses.setObjectName("formLayout_DialogExpenses")
        self.lblStudentID = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentID.setFont(font)
        self.lblStudentID.setObjectName("lblStudentID")
        self.formLayout_DialogExpenses.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStudentID)
        self.txtStudentID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtStudentID.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtStudentID.setFont(font)
        self.txtStudentID.setObjectName("txtStudentID")
        self.formLayout_DialogExpenses.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtStudentID)
        self.lblFirstName = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.formLayout_DialogExpenses.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblFirstName)
        self.txtFirstName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtFirstName.setFont(font)
        self.txtFirstName.setObjectName("txtFirstName")
        self.formLayout_DialogExpenses.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtFirstName)
        self.lblLastName = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.formLayout_DialogExpenses.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblLastName)
        self.txtLastName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtLastName.setFont(font)
        self.txtLastName.setObjectName("txtLastName")
        self.formLayout_DialogExpenses.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtLastName)
        self.lblGender = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender.setFont(font)
        self.lblGender.setObjectName("lblGender")
        self.formLayout_DialogExpenses.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.cmbGender = QtWidgets.QComboBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cmbGender.setFont(font)
        self.cmbGender.setObjectName("cmbGender")
        self.cmbGender.addItem("")
        self.cmbGender.addItem("")
        self.cmbGender.addItem("")
        self.formLayout_DialogExpenses.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbGender)
        self.lblGender_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender_2.setFont(font)
        self.lblGender_2.setObjectName("lblGender_2")
        self.formLayout_DialogExpenses.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblGender_2)
        self.lblGender_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender_3.setFont(font)
        self.lblGender_3.setObjectName("lblGender_3")
        self.formLayout_DialogExpenses.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblGender_3)
        self.lblGender_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender_4.setFont(font)
        self.lblGender_4.setObjectName("lblGender_4")
        self.formLayout_DialogExpenses.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblGender_4)
        self.lblGender_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender_5.setFont(font)
        self.lblGender_5.setObjectName("lblGender_5")
        self.formLayout_DialogExpenses.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblGender_5)
        self.lblGender_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGender_6.setFont(font)
        self.lblGender_6.setObjectName("lblGender_6")
        self.formLayout_DialogExpenses.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblGender_6)
        self.txtEmail = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtEmail.setFont(font)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout_DialogExpenses.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.txtAddress = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtAddress.setFont(font)
        self.txtAddress.setObjectName("txtAddress")
        self.formLayout_DialogExpenses.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtAddress)
        self.txtCredits = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCredits.setFont(font)
        self.txtCredits.setObjectName("txtCredits")
        self.formLayout_DialogExpenses.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtCredits)
        self.txtCurrentStatus = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCurrentStatus.setFont(font)
        self.txtCurrentStatus.setObjectName("txtCurrentStatus")
        self.formLayout_DialogExpenses.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtCurrentStatus)
        self.txtMajor = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtMajor.setFont(font)
        self.txtMajor.setObjectName("txtMajor")
        self.formLayout_DialogExpenses.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtMajor)
        self.frame = QtWidgets.QFrame(StudentsDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.formLayoutWidget_2.raise_()

        self.retranslateUi(StudentsDialog)
        self.buttonBox.accepted.connect(StudentsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(StudentsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StudentsDialog)

        self.listValues = listValues
        self.initialSetup()

    def retranslateUi(self, StudentsDialog):
        _translate = QtCore.QCoreApplication.translate
        StudentsDialog.setWindowTitle(_translate("StudentsDialog", "Students Dialog"))
        self.lblStudentID.setText(_translate("StudentsDialog", "Student ID: "))
        self.lblFirstName.setText(_translate("StudentsDialog", "First Name:"))
        self.lblLastName.setText(_translate("StudentsDialog", "Last Name:"))
        self.lblGender.setText(_translate("StudentsDialog", "Gender:"))
        self.cmbGender.setItemText(0, _translate("StudentsDialog", "M"))
        self.cmbGender.setItemText(1, _translate("StudentsDialog", "F"))
        self.cmbGender.setItemText(2, _translate("StudentsDialog", "O"))
        self.lblGender_2.setText(_translate("StudentsDialog", "Email:"))
        self.lblGender_3.setText(_translate("StudentsDialog", "Address:"))
        self.lblGender_4.setText(_translate("StudentsDialog", "Credits:"))
        self.lblGender_5.setText(_translate("StudentsDialog", "Current Status:"))
        self.lblGender_6.setText(_translate("StudentsDialog", "Major:"))

#####################     End UI Generation     #####################

    def initialSetup(self):
        print()
        self.setValues()

    #########################################################################
    #                                                                       #
    #                            Events                                     #
    #                                                                       #
    #########################################################################

    def setValues(self):
        if self.listValues == None:
            return

        self.txtStudentID.setText(self.listValues[0])
        self.txtFirstName.setText(self.listValues[1])
        self.txtLastName.setText(self.listValues[2])
        self.cmbGender.setCurrentText(self.listValues[3])
        self.txtEmail.setText(self.listValues[4])
        self.txtAddress.setText(self.listValues[5])
        self.txtCredits.setText(self.listValues[6])
        self.txtCurrentStatus.setText(self.listValues[7])
        self.txtMajor.setText(self.listValues[8])


    def getValues(self):
        listResult = []
        listResult.append(self.txtStudentID.text())
        listResult.append(self.txtFirstName.text())
        listResult.append(self.txtLastName.text())
        listResult.append(self.cmbGender.currentText())
        listResult.append(self.txtEmail.text())
        listResult.append(self.txtAddress.text())
        listResult.append(self.txtCredits.text())
        listResult.append(self.txtCurrentStatus.text())
        listResult.append(self.txtMajor.text())

        return listResult


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentsDialog = QtWidgets.QDialog()
    ui = Ui_StudentsDialog()
    ui.setupUi(StudentsDialog, None)
    StudentsDialog.show()
    sys.exit(app.exec_())
