# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ClassDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassDialog(object):
    def setupUi(self, ClassDialog):
        ClassDialog.setObjectName("ClassDialog")
        ClassDialog.resize(400, 140)
        self.buttonBox = QtWidgets.QDialogButtonBox(ClassDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(ClassDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 381, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_DialogExpenses = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_DialogExpenses.setContentsMargins(6, 6, 6, 6)
        self.formLayout_DialogExpenses.setObjectName("formLayout_DialogExpenses")
        self.lblStudentID = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentID.setFont(font)
        self.lblStudentID.setObjectName("lblStudentID")
        self.formLayout_DialogExpenses.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStudentID)
        self.txtStudentID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtStudentID.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtStudentID.setFont(font)
        self.txtStudentID.setObjectName("txtStudentID")
        self.formLayout_DialogExpenses.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtStudentID)
        self.lblSemesterID = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblSemesterID.setFont(font)
        self.lblSemesterID.setObjectName("lblSemesterID")
        self.formLayout_DialogExpenses.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblSemesterID)
        self.txtSemesterID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtSemesterID.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtSemesterID.setFont(font)
        self.txtSemesterID.setObjectName("txtSemesterID")
        self.formLayout_DialogExpenses.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtSemesterID)
        self.lblClassID = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblClassID.setFont(font)
        self.lblClassID.setObjectName("lblClassID")
        self.formLayout_DialogExpenses.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblClassID)
        self.txtClassID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtClassID.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtClassID.setFont(font)
        self.txtClassID.setObjectName("txtClassID")
        self.formLayout_DialogExpenses.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtClassID)
        self.frame = QtWidgets.QFrame(ClassDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.formLayoutWidget_2.raise_()

        self.retranslateUi(ClassDialog)
        self.buttonBox.accepted.connect(ClassDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ClassDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ClassDialog)

    def retranslateUi(self, ClassDialog):
        _translate = QtCore.QCoreApplication.translate
        ClassDialog.setWindowTitle(_translate("ClassDialog", "Class Dialog"))
        self.lblStudentID.setText(_translate("ClassDialog", "Student ID: "))
        self.lblSemesterID.setText(_translate("ClassDialog", "Semester ID:"))
        self.lblClassID.setText(_translate("ClassDialog", "Class ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClassDialog = QtWidgets.QDialog()
    ui = Ui_ClassDialog()
    ui.setupUi(ClassDialog)
    ClassDialog.show()
    sys.exit(app.exec_())
