# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file '.\ClassTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#########################################################################
#                                                                       #
#                            UI Generation                              #
#                                                                       #
#########################################################################

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication, QTime

import mysql.connector
from PyQt5.QtWidgets import QMessageBox

import ClassDialog
import datetime

QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)  # Enable high DPI scaling
QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)  # Use high DPI icons

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 681, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(700, 80, 81, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNew = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnNew.setFont(font)
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout.addWidget(self.btnNew)
        self.btnEdit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnClose = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClose.setOrientation(QtCore.Qt.Vertical)
        self.btnClose.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btnClose.setCenterButtons(False)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 10, 221, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblClassID = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblClassID.setFont(font)
        self.lblClassID.setObjectName("lblClassID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblClassID)
        self.lblSemesterID = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblSemesterID.setFont(font)
        self.lblSemesterID.setObjectName("lblSemesterID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblSemesterID)
        self.txtClassID = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtClassID.setFont(font)
        self.txtClassID.setText("")
        self.txtClassID.setObjectName("txtClassID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtClassID)
        self.txtSemesterID = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtSemesterID.setFont(font)
        self.txtSemesterID.setText("")
        self.txtSemesterID.setObjectName("txtSemesterID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtSemesterID)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 10, 311, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblDays = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblDays.setFont(font)
        self.lblDays.setObjectName("lblDays")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblDays)
        self.txtDays = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtDays.setFont(font)
        self.txtDays.setText("")
        self.txtDays.setObjectName("txtDays")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtDays)
        self.lblStartTime = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStartTime.setFont(font)
        self.lblStartTime.setObjectName("lblStartTime")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblStartTime)
        self.timeStartTime = QtWidgets.QTimeEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.timeStartTime.setFont(font)
        self.timeStartTime.setCalendarPopup(False)
        self.timeStartTime.setObjectName("timeStartTime")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeStartTime)
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(10, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitle.setFont(font)
        self.lblTitle.setAcceptDrops(False)
        self.lblTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTitle.setAutoFillBackground(False)
        self.lblTitle.setStyleSheet("background-color: rgb(22, 9, 88);\n"
"color: rgb(255, 255, 255);")
        self.lblTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTitle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblTitle.setLineWidth(3)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(700, 10, 81, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSearch = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout_2.addWidget(self.btnSearch)
        self.btnClear = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout_2.addWidget(self.btnClear)
        self.frameTop = QtWidgets.QFrame(Dialog)
        self.frameTop.setGeometry(QtCore.QRect(140, 10, 641, 61))
        self.frameTop.setStyleSheet("color: rgb(255, 255, 0);")
        self.frameTop.setFrameShape(QtWidgets.QFrame.Box)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTop.setLineWidth(2)
        self.frameTop.setObjectName("frameTop")
        self.frameRight = QtWidgets.QFrame(Dialog)
        self.frameRight.setGeometry(QtCore.QRect(700, 80, 81, 491))
        self.frameRight.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameRight.setLineWidth(2)
        self.frameRight.setObjectName("frameRight")
        self.frameRight.raise_()
        self.frameTop.raise_()
        self.horizontalLayoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.lblTitle.raise_()
        self.verticalLayoutWidget_2.raise_()

        self.retranslateUi(Dialog)
        self.btnClose.accepted.connect(Dialog.accept) # type: ignore
        self.btnClose.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Class Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Class ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Semester ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Course ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Professor ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Days"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "End Time"))
        self.btnNew.setText(_translate("Dialog", "New"))
        self.btnEdit.setText(_translate("Dialog", "Edit"))
        self.btnDelete.setText(_translate("Dialog", "Delete"))
        self.lblClassID.setText(_translate("Dialog", "Class ID:"))
        self.lblSemesterID.setText(_translate("Dialog", "Semester ID:"))
        self.lblDays.setText(_translate("Dialog", "Days:"))
        self.lblStartTime.setText(_translate("Dialog", "Start Time:"))
        self.lblTitle.setText(_translate("Dialog", "Class Table"))
        self.btnSearch.setText(_translate("Dialog", "Search"))
        self.btnClear.setText(_translate("Dialog", "Clear"))


#####################     End UI Generation     #####################

    def initialSetup(self):
        self.setupEvents()
        self.setupDatabase()
        self.refreshClass()
        # self.setupDatabase()
        # self.setupCombobox()
        # self.setValues()

    #########################################################################
    #                                                                       #
    #                            Events                                     #
    #                                                                       #
    #########################################################################

    def setupEvents(self):
        self.btnNew.clicked.connect(self.btnNewClass_clicked)
        self.btnEdit.clicked.connect(self.btnEditClass_clicked)
        self.btnDelete.clicked.connect(self.btnDeleteClass_clicked)
        self.btnSearch.clicked.connect(self.btnSearch_clicked)
        self.btnClear.clicked.connect(self.btnClear_clicked)

    def btnNewClass_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = ClassDialog.Ui_ClassDialog()
        form.setupUi(Dialog, None)  # None -> no list, no need to send data when creating a new record
        result = Dialog.exec_()

        if result == 1:  # This means the user clicked OK
            #   Get the list of results from dialog
            listValues = form.getValues()

            cursor = self.cnx.cursor()

            query = "Select * From class"

            cursor.execute(query)

            largestID = 0
            # Retreive the largest ID
            for (Class_ID, Semester_ID, Course_ID, Professor_ID, Days, StartTime, EndTime) in cursor:
                if (Class_ID > largestID):
                    largestID = Class_ID

            largestID += 1
            listValues[ 0 ] = str(largestID)

            print(listValues)

            # Insert the values in the database
            self.insertClass(listValues)

            # Refresh the table
            self.refreshClass()

    def btnEditClass_clicked(self):
        currentRow = self.tableWidget.currentRow()

        print("Edit clicked")

        if currentRow == -1:
            QMessageBox.warning(None, "Select Row", "Please select row first")
            return

        listValues = [ ]
        listValues.append(self.tableWidget.item(currentRow, 0).text())
        listValues.append(self.tableWidget.item(currentRow, 1).text())
        listValues.append(self.tableWidget.item(currentRow, 2).text())
        listValues.append(self.tableWidget.item(currentRow, 3).text())
        listValues.append(self.tableWidget.item(currentRow, 4).text())
        listValues.append(QTime.fromString(self.tableWidget.item(currentRow, 5).text(), "hh:mm:ss"))
        listValues.append(QTime.fromString(self.tableWidget.item(currentRow, 6).text(), "hh:mm:ss"))

        print(listValues)

        Dialog = QtWidgets.QDialog()
        form = ClassDialog.Ui_ClassDialog()
        form.setupUi(Dialog, listValues)
        result = Dialog.exec_()

        if result == 1:  # This means the user clicked OK
            #   Get the list of results from dialog
            newValues = form.getValues()
            newValues[ 0 ] = listValues[ 0 ]  # Set the ID to the original value

            # Insert the values in the table
            # rowCount = self.tblCategories.rowCount()
            # self.tblCategories.insertRow(rowCount)  # Create new row at the end
            # self.tblCategories.setItem(rowCount, 0, QTableWidgetItem(listValues[0]))
            # self.tblCategories.setItem(rowCount, 1, QTableWidgetItem(listValues[1]))

            # Insert the values in the database
            self.updateClass(newValues)

            # Refresh the table
            self.refreshClass()

    def btnDeleteClass_clicked(self):
        currentRow = self.tableWidget.currentRow()

        if currentRow == -1:
            QMessageBox.warning(None, "Select Row", "Please select row first")
            return

        answer = QMessageBox.question(
            None,
            "Delete row?",
            "Are you sure you want to delete this row?",
            QMessageBox.StandardButton.Yes |
            QMessageBox.StandardButton.No
        )

        if answer == QMessageBox.StandardButton.Yes:
            ID = self.tableWidget.item(currentRow, 0).text()

            # Delete the values in the database
            self.deleteClass(ID)
            self.refreshClass()

    def btnSearch_clicked(self):
        Class_ID = self.txtClassID.text()
        Semester_ID = self.txtSemesterID.text()
        Days = self.txtDays.text()
        StartTime = self.timeStartTime.time()

        self.filterClass(Class_ID, Semester_ID, Days, StartTime)

    def btnClear_clicked(self):
        self.txtClassID.setText("")
        self.txtSemesterID.setText("")
        self.txtDays.setText("")
        self.timeStartTime.setTime(QTime(0, 0, 0))

        self.refreshClass()


    #########################################################################
    #                                                                       #
    #                            Database                                   #
    #                                                                       #
    #########################################################################

    def setupDatabase(self):
        self.connect()

    def connect(self):
        self.cnx = mysql.connector.connect(user="root",
                                            password="12345678",
                                            host="127.0.0.1",
                                            database="tracle")

    def refreshClass(self):
        self.tableWidget.setRowCount(0)
        cursor = self.cnx.cursor()

        query = "Select * From class"

        cursor.execute(query)

        for(Class_ID, Semester_ID, Course_ID, Professor_ID, Days, StartTime, EndTime) in cursor:
            print(Class_ID, Semester_ID, Course_ID, Professor_ID, Days, StartTime, EndTime)
            rowCount = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rowCount)
            self.tableWidget.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(str(Class_ID)))
            self.tableWidget.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(str(Semester_ID)))
            self.tableWidget.setItem(rowCount, 2, QtWidgets.QTableWidgetItem(str(Course_ID)))
            self.tableWidget.setItem(rowCount, 3, QtWidgets.QTableWidgetItem(str(Professor_ID)))
            self.tableWidget.setItem(rowCount, 4, QtWidgets.QTableWidgetItem(Days))
            self.tableWidget.setItem(rowCount, 5, QtWidgets.QTableWidgetItem(str(StartTime)))
            self.tableWidget.setItem(rowCount, 6, QtWidgets.QTableWidgetItem(str(EndTime)))

        cursor.close()

    def insertClass(self, listValues):
        cursor = self.cnx.cursor()

        query = "Insert Into class " \
                "(Class_ID, Semester_ID, Course_ID, Professor_ID, Days, StartTime, EndTime) " \
                "Values (%s, %s, %s, %s, %s, %s, %s)"

        listValues[5] = listValues[5].toString("HH:mm")
        listValues[6] = listValues[6].toString("HH:mm")

        print(listValues)

        cursor.execute(query, listValues)

        self.cnx.commit()

        cursor.close()

    def updateClass(self, listValues):
        cursor = self.cnx.cursor()

        query = "Update class " \
                "Set Semester_ID = %s, Course_ID = %s, Professor_ID = %s, Days = %s, StartTime = %s, EndTime = %s " \
                "Where Class_ID = %s"

        listValues[5] = listValues[5].toString("HH:mm")
        listValues[6] = listValues[6].toString("HH:mm")

        listValues.append(listValues.pop(0))

        print(listValues)

        cursor.execute(query, listValues)

        self.cnx.commit()

        cursor.close()

    def deleteClass(self, ID):
        cursor = self.cnx.cursor()

        query = "Delete From class Where Class_ID = %s"

        cursor.execute(query, (ID, ))

        self.cnx.commit()

        cursor.close()

    def filterClass(self, _Class_ID, _Semester_ID, _Days, _StartTime):
        self.tableWidget.setRowCount(0)

        cursor = self.cnx.cursor()

        query = "Select * " \
                "From class " \
                "WHERE (Class_ID = %s OR %s = '') " \
                "AND (Semester_ID = %s OR %s = '') " \
                "AND (Days = %s OR %s = '') " \
                "AND (StartTime = %s OR %s = '00:00')"


        values = []

        values.append(_Class_ID)
        values.append(_Class_ID)
        values.append(_Semester_ID)
        values.append(_Semester_ID)
        values.append(_Days)
        values.append(_Days)
        values.append(_StartTime.toString("HH:mm"))
        values.append(_StartTime.toString("HH:mm"))

        print(values)

        cursor.execute(query, values)

        for (Class_ID, Semester_ID, Course_ID, Professor_ID, Days, StartTime, EndTime) in cursor:
            rowCount = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rowCount)
            self.tableWidget.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(str(Class_ID)))
            self.tableWidget.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(str(Semester_ID)))
            self.tableWidget.setItem(rowCount, 2, QtWidgets.QTableWidgetItem(str(Course_ID)))
            self.tableWidget.setItem(rowCount, 3, QtWidgets.QTableWidgetItem(str(Professor_ID)))
            self.tableWidget.setItem(rowCount, 4, QtWidgets.QTableWidgetItem(Days))
            self.tableWidget.setItem(rowCount, 5, QtWidgets.QTableWidgetItem(str(StartTime)))
            self.tableWidget.setItem(rowCount, 6, QtWidgets.QTableWidgetItem(str(EndTime)))

        cursor.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
