# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#########################################################################
#                                                                       #
#                            UI Generation                              #
#                                                                       #
#########################################################################

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication

import AttendanceTable
import ClassTable
import CoursesTable
import Credits
import OfflineHelp
import Reports
import SemesterTable
import StudentsTable
import socket
import webbrowser
import mysql.connector

QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)  # Enable high DPI scaling
QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)  # Use high DPI icons


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/blue200px-Temple_T_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.323, y1:0.256, x2:0.783818, y2:0.665318, stop:0.0113636 rgba(0, 144, 255, 255), stop:0.142045 rgba(0, 0, 96, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelGui1 = QtWidgets.QLabel(self.centralwidget)
        self.labelGui1.setGeometry(QtCore.QRect(0, 50, 1301, 91))
        self.labelGui1.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.labelGui1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelGui1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelGui1.setLineWidth(3)
        self.labelGui1.setMidLineWidth(0)
        self.labelGui1.setText("")
        self.labelGui1.setScaledContents(False)
        self.labelGui1.setOpenExternalLinks(False)
        self.labelGui1.setObjectName("labelGui1")
        self.labelGui2 = QtWidgets.QLabel(self.centralwidget)
        self.labelGui2.setGeometry(QtCore.QRect(0, 190, 1281, 481))
        self.labelGui2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelGui2.setText("")
        self.labelGui2.setObjectName("labelGui2")
        self.labelGui3 = QtWidgets.QLabel(self.centralwidget)
        self.labelGui3.setGeometry(QtCore.QRect(10, 200, 381, 461))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelGui3.setFont(font)
        self.labelGui3.setAcceptDrops(False)
        self.labelGui3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.495, y2:0.153409, stop:0 rgba(52, 123, 255, 255), stop:1 rgba(0, 0, 64, 255));")
        self.labelGui3.setText("")
        self.labelGui3.setObjectName("labelGui3")
        self.labelGui4 = QtWidgets.QLabel(self.centralwidget)
        self.labelGui4.setGeometry(QtCore.QRect(400, 200, 891, 461))
        self.labelGui4.setAutoFillBackground(False)
        self.labelGui4.setStyleSheet("background-color: rgb(58, 133, 225);")
        self.labelGui4.setText("")
        self.labelGui4.setPixmap(QtGui.QPixmap("media/trans-blue300px-Temple_T_logo.png"))
        self.labelGui4.setScaledContents(False)
        self.labelGui4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGui4.setObjectName("labelGui4")
        self.btnHelp = QtWidgets.QPushButton(self.centralwidget)
        self.btnHelp.setGeometry(QtCore.QRect(90, 390, 201, 71))
        self.btnHelp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHelp.setAcceptDrops(False)
        self.btnHelp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnHelp.setAutoFillBackground(False)
        self.btnHelp.setStyleSheet("border-image: url(media/Button1.jpg);")
        self.btnHelp.setText("")
        self.btnHelp.setCheckable(False)
        self.btnHelp.setAutoDefault(False)
        self.btnHelp.setDefault(False)
        self.btnHelp.setFlat(False)
        self.btnHelp.setObjectName("btnHelp")
        self.btnCanvas = QtWidgets.QPushButton(self.centralwidget)
        self.btnCanvas.setGeometry(QtCore.QRect(90, 480, 201, 71))
        self.btnCanvas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCanvas.setAcceptDrops(False)
        self.btnCanvas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCanvas.setAutoFillBackground(False)
        self.btnCanvas.setStyleSheet("border-image: url(media/Button2.jpg);")
        self.btnCanvas.setText("")
        self.btnCanvas.setCheckable(False)
        self.btnCanvas.setAutoDefault(False)
        self.btnCanvas.setDefault(False)
        self.btnCanvas.setFlat(False)
        self.btnCanvas.setObjectName("btnCanvas")
        self.btnDonate = QtWidgets.QPushButton(self.centralwidget)
        self.btnDonate.setGeometry(QtCore.QRect(90, 570, 201, 71))
        self.btnDonate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDonate.setAcceptDrops(False)
        self.btnDonate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDonate.setAutoFillBackground(False)
        self.btnDonate.setStyleSheet("border-image: url(media/Button3.jpg);")
        self.btnDonate.setText("")
        self.btnDonate.setCheckable(False)
        self.btnDonate.setAutoDefault(False)
        self.btnDonate.setDefault(False)
        self.btnDonate.setFlat(False)
        self.btnDonate.setObjectName("btnDonate")
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        self.lblLogo.setGeometry(QtCore.QRect(40, 50, 251, 111))
        self.lblLogo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("media/logo1a.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.btnStudents = QtWidgets.QPushButton(self.centralwidget)
        self.btnStudents.setGeometry(QtCore.QRect(470, 250, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btnStudents.setFont(font)
        self.btnStudents.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStudents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnStudents.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnStudents.setIconSize(QtCore.QSize(40, 40))
        self.btnStudents.setObjectName("btnStudents")
        self.btnClass = QtWidgets.QPushButton(self.centralwidget)
        self.btnClass.setGeometry(QtCore.QRect(470, 350, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnClass.setFont(font)
        self.btnClass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClass.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnClass.setObjectName("btnClass")
        self.btnCourses = QtWidgets.QPushButton(self.centralwidget)
        self.btnCourses.setGeometry(QtCore.QRect(470, 450, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnCourses.setFont(font)
        self.btnCourses.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCourses.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCourses.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnCourses.setObjectName("btnCourses")
        self.btnAttendance = QtWidgets.QPushButton(self.centralwidget)
        self.btnAttendance.setGeometry(QtCore.QRect(860, 250, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnAttendance.setFont(font)
        self.btnAttendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAttendance.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnAttendance.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnAttendance.setObjectName("btnAttendance")
        self.btnSemester = QtWidgets.QPushButton(self.centralwidget)
        self.btnSemester.setGeometry(QtCore.QRect(860, 350, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnSemester.setFont(font)
        self.btnSemester.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSemester.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSemester.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnSemester.setObjectName("btnSemester")
        self.btnReports = QtWidgets.QPushButton(self.centralwidget)
        self.btnReports.setGeometry(QtCore.QRect(860, 450, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnReports.setFont(font)
        self.btnReports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnReports.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnReports.setObjectName("btnReports")
        self.btnOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.btnOriginal.setGeometry(QtCore.QRect(310, 110, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOriginal.setFont(font)
        self.btnOriginal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOriginal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnOriginal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.btnOriginal.setObjectName("btnOriginal")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 220, 331, 151))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.522682, y1:0.403409, x2:0.522318, y2:1, stop:0.142045 rgba(16, 85, 197, 255), stop:0.153409 rgba(9, 62, 157, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblWelcome = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lblWelcome.setFont(font)
        self.lblWelcome.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblWelcome.setObjectName("lblWelcome")
        self.verticalLayout.addWidget(self.lblWelcome, 0, QtCore.Qt.AlignHCenter)
        self.lblHostName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblHostName.setFont(font)
        self.lblHostName.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblHostName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHostName.setWordWrap(True)
        self.lblHostName.setObjectName("lblHostName")
        self.verticalLayout.addWidget(self.lblHostName)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 80, 331, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblLanguage = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblLanguage.setFont(font)
        self.lblLanguage.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblLanguage.setObjectName("lblLanguage")
        self.gridLayout_2.addWidget(self.lblLanguage, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lblSchemaName = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSchemaName.setFont(font)
        self.lblSchemaName.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblSchemaName.setWordWrap(True)
        self.lblSchemaName.setObjectName("lblSchemaName")
        self.gridLayout_2.addWidget(self.lblSchemaName, 1, 1, 1, 1)
        self.lblSchema = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblSchema.setFont(font)
        self.lblSchema.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblSchema.setObjectName("lblSchema")
        self.gridLayout_2.addWidget(self.lblSchema, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.cmbLanguage = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cmbLanguage.setFont(font)
        self.cmbLanguage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbLanguage.setObjectName("cmbLanguage")
        self.cmbLanguage.addItem("")
        self.cmbLanguage.addItem("")
        self.cmbLanguage.addItem("")
        self.gridLayout_2.addWidget(self.cmbLanguage, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 220, 301, 21))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lblBuild = QtWidgets.QLabel(self.centralwidget)
        self.lblBuild.setGeometry(QtCore.QRect(210, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBuild.setFont(font)
        self.lblBuild.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblBuild.setObjectName("lblBuild")
        self.btnCredits = QtWidgets.QPushButton(self.centralwidget)
        self.btnCredits.setGeometry(QtCore.QRect(470, 550, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnCredits.setFont(font)
        self.btnCredits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCredits.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCredits.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnCredits.setObjectName("btnCredits")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(860, 550, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnExit.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.initialSetup()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tpera"))
        self.btnStudents.setText(_translate("MainWindow", "Students"))
        self.btnClass.setText(_translate("MainWindow", "Class"))
        self.btnCourses.setText(_translate("MainWindow", "Courses"))
        self.btnAttendance.setText(_translate("MainWindow", "Attendance"))
        self.btnSemester.setText(_translate("MainWindow", "Semester"))
        self.btnReports.setText(_translate("MainWindow", "Reports"))
        self.btnOriginal.setText(_translate("MainWindow", "CREDIT TO ORACLE FOR ORIGINAL OPERA DESIGN"))
        self.lblWelcome.setText(_translate("MainWindow", "Welcome,"))
        self.lblHostName.setText(_translate("MainWindow", "get_host_name"))
        self.lblLanguage.setText(_translate("MainWindow", "Language: "))
        self.lblSchemaName.setText(_translate("MainWindow", "get_schema_name"))
        self.lblSchema.setText(_translate("MainWindow", "Schema: "))
        self.cmbLanguage.setItemText(0, _translate("MainWindow", "English"))
        self.cmbLanguage.setItemText(1, _translate("MainWindow", "日本語 (Not supported)"))
        self.cmbLanguage.setItemText(2, _translate("MainWindow", "Others (Not supported)"))
        self.label_6.setText(_translate("MainWindow", "GUI Designer: Abimanyu"))
        self.lblBuild.setText(_translate("MainWindow", "Alpha build - v0.0.6"))
        self.btnCredits.setText(_translate("MainWindow", "Credits"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
#import new_rc

#####################     End UI Generation     #####################

    def initialSetup(self):
        self.setupEvents()
        self.setupHostName()
        self.setupDatabase()

    #########################################################################
    #                                                                       #
    #                            Events                                     #
    #                                                                       #
    #########################################################################

    def setupEvents(self):
        self.btnStudents.clicked.connect(self.btnStudents_clicked)
        self.btnClass.clicked.connect(self.btnClass_clicked)
        self.btnCourses.clicked.connect(self.btnCourses_clicked)
        self.btnAttendance.clicked.connect(self.btnAttendance_clicked)
        self.btnSemester.clicked.connect(self.btnSemester_clicked)
        self.btnReports.clicked.connect(self.btnReports_clicked)
        self.btnCredits.clicked.connect(self.btnCredits_clicked)
        self.btnExit.clicked.connect(self.btnExit_clicked)
        self.btnHelp.clicked.connect(self.btnHelp_clicked)
        self.btnCanvas.clicked.connect(self.btnCanvas_clicked)
        self.btnDonate.clicked.connect(self.btnDonate_clicked)
        self.btnOriginal.clicked.connect(self.btnOriginal_clicked)

    def setupHostName(self):
        hostName = self.getHostName()
        self.lblHostName.setText(hostName)

    def btnStudents_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = StudentsTable.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnClass_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = ClassTable.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnCourses_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = CoursesTable.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnAttendance_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = AttendanceTable.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnSemester_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = SemesterTable.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnCredits_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = Credits.Ui_CreditsDialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnReports_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = Reports.Ui_ReportsDialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnExit_clicked(self):
        sys.exit()

    def btnOriginal_clicked(self):
        webbrowser.open('https://www.oracle.com/hospitality/products/opera-property-services/')

    def btnHelp_clicked(self):
        Dialog = QtWidgets.QDialog()
        form = OfflineHelp.Ui_Dialog()
        form.setupUi(Dialog)
        result = Dialog.exec_()

    def btnCanvas_clicked(self):
        webbrowser.open('https://templeu.instructure.com/')

    def btnDonate_clicked(self):
        webbrowser.open('https://www.paypal.com/signin')

    #########################################################################
    #                                                                       #
    #                            Others                                     #
    #                                                                       #
    #########################################################################

    def getHostName(self):
        try:
            return socket.gethostname()
        except socket.error as e:
            print("Error:", e)
            return "CANNOT-BE-RETREIVED"

    def setupDatabase(self):
        self.connect()

    def connect(self, user="root", password="12345678", host="127.0.0.1", database="tracle"):
        try:
            self.cnx = mysql.connector.connect(user=user,
                                               password=password,
                                               host=host,
                                               database=database)
        except Exception as e:
            print("Error:", e)
            print("Database cannot be connected.")
            # Update schema name
            self.lblSchemaName.setText("CANNOT-BE-REACHED")
            return None
        else:
            # Update schema name
            self.lblSchemaName.setText(database)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
